name: Build and publish snapshots
on:
  push:
    branches: [ javabuild ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: javabuild
    - name: Download OpenJDK 19
      id: download
      uses: oracle-actions/setup-java@v1
      with:
        website: jdk.java.net
        release: 19
        install: false
    - name: Setup Java and Apache Maven
      uses: actions/setup-java@v3
      with:
        distribution: jdkfile
        jdkFile: ${{ steps.download.outputs.archive }}
        java-version: ${{ steps.download.outputs.version }}
        server-id: gluon-nexus
        server-username: MAVEN_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
    - name: Checkout tools repo
      run: |
        echo $JAVA_HOME
        cd $GITHUB_WORKSPACE
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
    - name: Install rustup
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - name: Download and extract JEXTRACT
      run: |
        echo $JAVA_HOME
        download_url="https://download.java.net/java/early_access/jextract/2/openjdk-19-jextract+2-3_linux-x64_bin.tar.gz"
        wget -q --show-progress -O $RUNNER_TEMP/jextract.tar.gz $download_url
        tar -xvzf $RUNNER_TEMP/jextract.tar.gz -C $GITHUB_WORKSPACE
    - name: Build
      run: |
        export PATH=$GITHUB_WORKSPACE/depot_tools/:$PATH
        echo $JAVA_HOME
        make java PLATFORM=unix JEXTRACT=$GITHUB_WORKSPACE/jextract-19 JDK=$JAVA_HOME TARGET_ARCH=x64
    - name: Deploy snapshot
      run: |
        cd src/java/tring
        mvn -Dclassifier=linux deploy
      env:
        MAVEN_USERNAME: ${{ secrets.GLUON_NEXUS_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.GLUON_NEXUS_PASSWORD }}